"use client";
import { FormEvent, useState } from "react";
import { ArrowRight, CalendarDays, Plane, ShieldCheck, Trophy, X } from "lucide-react";
import styles from "./page.module.css";

type Career={eventName:string;location:string;budget:number;days:number;scale:string;eventDate:string};
type Status="Available"|"Invited"|"Interested"|"Declined"|"Confirmed";
type Contact={id:number;name:string;country:string;aircraft:string;fee:number;reply:number;status:Status;hotel:number;fuel:number;support:number};

const profiles=[["Regional AirShow",650000],["National AirShow",1250000],["International AirShow",2400000]] as const;
const initialContacts:Contact[]=[
{id:1,name:"Falcon Demo Team",country:"Poland",aircraft:"F-16",fee:85000,reply:0,status:"Available",hotel:12000,fuel:18000,support:7000},
{id:2,name:"Baltic Jet Team",country:"Lithuania",aircraft:"L-39 × 6",fee:145000,reply:0,status:"Available",hotel:26000,fuel:32000,support:14000},
{id:3,name:"Heritage Flight",country:"United Kingdom",aircraft:"Spitfire",fee:62000,reply:0,status:"Available",hotel:9000,fuel:11000,support:6000},
{id:4,name:"Alpine Solo Display",country:"Switzerland",aircraft:"F/A-18",fee:110000,reply:0,status:"Available",hotel:14000,fuel:24000,support:9000}
];

export default function Home(){const [career,setCareer]=useState<Career|null>(null);const [creating,setCreating]=useState(false);if(career)return <Dashboard career={career}/>;if(creating)return <CareerSetup onBack={()=>setCreating(false)} onCreate={setCareer}/>;return <main className={styles.landing}><div className={styles.eyebrow}>AIRSHOW MANAGEMENT SIMULATION</div><section className={styles.hero}><div><span className={styles.kicker}>BUILD · ORGANIZE · DELIVER</span><h1>AIRSHOW<br/><b>MANAGER</b></h1><p>Od pierwszego telefonu do zespołu pokazowego aż po otwarcie bram. Zbuduj organizację, zabezpiecz budżet i dowieź dzień pokazu.</p><div className={styles.actions}><button onClick={()=>setCreating(true)}>Nowa kariera <ArrowRight size={18}/></button><button className={styles.secondary} disabled>Kontynuuj <small>brak zapisu</small></button></div></div><div className={styles.radar}><Plane size={42}/><span>OPS / 001</span></div></section><div className={styles.featureRow}><Feature icon={<CalendarDays/>} title="Pełny sezon" text="Od planowania do Event Day"/><Feature icon={<ShieldCheck/>} title="Operations" text="Bezpieczeństwo i logistyka"/><Feature icon={<Trophy/>} title="Career" text="Buduj reputację organizatora"/></div></main>}

function CareerSetup({onBack,onCreate}:{onBack:()=>void;onCreate:(c:Career)=>void}){const [name,setName]=useState("Baltic Wings AirShow"),[country,setCountry]=useState("Poland"),[date,setDate]=useState("2027-08-28"),[level,setLevel]=useState(0);const submit=(e:FormEvent)=>{e.preventDefault();onCreate({eventName:name||"My AirShow",location:country,eventDate:date,scale:profiles[level][0],budget:profiles[level][1],days:332})};return <main className={styles.setup}><button className={styles.back} onClick={onBack}>← BACK</button><form onSubmit={submit} className={styles.setupGrid}><section><span className={styles.kicker}>NEW CAREER / SEASON 01</span><h1>Build your first <b>AirShow.</b></h1><p>Ustal profil organizacji. Te decyzje będą podstawą pierwszego sezonu.</p><label>EVENT NAME<input value={name} onChange={e=>setName(e.target.value)}/></label><div className={styles.twoFields}><label>HOST COUNTRY<select value={country} onChange={e=>setCountry(e.target.value)}><option>Poland</option><option>Czech Republic</option><option>Germany</option><option>United Kingdom</option><option>France</option></select></label><label>EVENT DATE<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div></section><section className={styles.scalePanel}><span className={styles.kicker}>STARTING PROFILE</span><h2>Select event scale</h2>{profiles.map((x,i)=><button type="button" key={x[0]} className={level===i?styles.scaleActive:styles.scaleCard} onClick={()=>setLevel(i)}><strong>{x[0]}</strong><span>{money(x[1])}</span></button>)}<div className={styles.startSummary}><span>OPENING CASH</span><strong>{money(profiles[level][1])}</strong></div><button className={styles.launch}>ESTABLISH ORGANIZATION →</button></section></form></main>}

function Dashboard({career}:{career:Career}){const [days,setDays]=useState(career.days),[cash,setCash]=useState(career.budget),[tab,setTab]=useState("Overview"),[feed,setFeed]=useState(["Organization established. Season planning has begun."]),[contacts,setContacts]=useState(initialContacts),[selected,setSelected]=useState<number|null>(null);
const invite=(id:number)=>{setContacts(x=>x.map(c=>c.id===id?{...c,status:"Invited",reply:days-4}:c));setFeed(x=>["Invitation sent. Awaiting participant response.",...x].slice(0,5))};
const advance=(amount:number)=>{const next=Math.max(0,days-amount);setDays(next);setContacts(current=>current.map(c=>{if(c.status==="Invited"&&next<=c.reply){const ok=c.id!==4;setFeed(x=>[`${c.name}: ${ok?"interested — requirements received":"unable to attend this season"}.`,...x].slice(0,5));return {...c,status:ok?"Interested":"Declined"}}return c}));};
const sign=(id:number,discount=0)=>{const c=contacts.find(x=>x.id===id);if(!c)return;const total=Math.round((c.fee+c.hotel+c.fuel+c.support)*(1-discount));if(total>cash){setFeed(x=>["Contract blocked: insufficient available cash.",...x].slice(0,5));return}setCash(x=>x-total);setContacts(x=>x.map(y=>y.id===id?{...y,status:"Confirmed"}:y));setFeed(x=>[`${c.name} confirmed. Contract value: ${money(total)}.`,...x].slice(0,5));setSelected(null)};
const confirmed=contacts.filter(c=>c.status==="Confirmed").length;
return <main className={styles.app}><aside><div className={styles.brand}><Plane/><b>ASM</b></div><nav>{["Overview","Operations","Participants","Sponsors","Team","Infrastructure","Ticketing","Marketing","Finance"].map(x=><button onClick={()=>setTab(x)} className={tab===x?styles.active:""} key={x}>{x}</button>)}</nav><div className={styles.season}>SEASON 01<br/><strong>{career.scale}</strong></div></aside><section className={styles.workspace}><header><div><span>OPERATIONS CENTER</span><h2>{career.eventName}</h2><p>{career.location} · {career.eventDate}</p></div><div className={styles.timebox}><div className={styles.countdown}><b>{days}</b><span>DAYS TO AIRSHOW</span></div><div className={styles.timeControls}><button onClick={()=>advance(1)}>+1 DAY</button><button onClick={()=>advance(7)}>+7 DAYS</button></div></div></header>{tab==="Participants"?<Participants contacts={contacts} invite={invite} open={setSelected}/>:<Overview days={days} cash={cash} confirmed={confirmed} feed={feed}/>}</section>{selected&&<Contract contact={contacts.find(c=>c.id===selected)!} cash={cash} close={()=>setSelected(null)} sign={sign}/>}</main>}

function Overview({days,cash,confirmed,feed}:{days:number;cash:number;confirmed:number;feed:string[]}){return <><div className={styles.metrics}><Metric label="AVAILABLE CASH" value={money(cash)} sub="Current balance"/><Metric label="REPUTATION" value="12 / 100" sub="Regional organizer"/><Metric label="CONFIRMED ACTS" value={String(confirmed)} sub="Signed contracts"/><Metric label="READINESS" value={confirmed?"12%":"4%"} sub="Planning phase"/></div><div className={styles.grid}><article className={styles.panel}><div className={styles.panelHead}><div><span>MISSION CONTROL</span><h3>Priority tasks</h3></div><b>4 OPEN</b></div>{["Zbuduj zespół operacyjny","Pozyskaj pierwszego sponsora","Potwierdź uczestnika","Ustal strategię biletów"].map((x,i)=><div className={styles.task} key={x}><span className={styles.taskNo}>0{i+1}</span><div><strong>{x}</strong><small>{Math.max(0,days-(i+1)*25)} days remaining</small></div><em>{i<2?"High":"Medium"}</em></div>)}</article><article className={styles.panel}><div className={styles.panelHead}><div><span>EVENT HEALTH</span><h3>Departments</h3></div></div>{[["Air Operations",8],["Commercial",4],["Safety",6],["Marketing",2]].map(([n,v])=><div className={styles.health} key={n as string}><div><span>{n}</span><b>{v}%</b></div><progress value={v as number} max="100"/></div>)}</article></div><div className={styles.timeline}><div className={styles.panelHead}><div><span>ORGANIZER LOG</span><h3>Latest events</h3></div><b>LIVE</b></div>{feed.map((x,i)=><div className={styles.logItem} key={i}><span>D-{days}</span><p>{x}</p></div>)}</div></>}

function Participants({contacts,invite,open}:{contacts:Contact[];invite:(id:number)=>void;open:(id:number)=>void}){return <section className={styles.participants}><div className={styles.sectionTitle}><div><span>PARTICIPANT RELATIONS</span><h3>Contacts & invitations</h3><p>Invite display teams. Replies arrive as game time advances.</p></div><b>{contacts.filter(c=>c.status==="Confirmed").length} CONFIRMED</b></div><div className={styles.contactList}>{contacts.map(c=><article className={styles.contact} key={c.id}><div className={styles.flag}>{c.country.slice(0,2).toUpperCase()}</div><div><span>{c.country} · {c.aircraft}</span><h4>{c.name}</h4><small>Base appearance fee: {money(c.fee)}</small></div><div className={styles.contactAction}><em className={styles["status"+c.status]}>{c.status}</em>{c.status==="Available"&&<button onClick={()=>invite(c.id)}>SEND INVITATION</button>}{c.status==="Invited"&&<small>Awaiting response</small>}{c.status==="Interested"&&<button onClick={()=>open(c.id)}>VIEW REQUIREMENTS</button>}{c.status==="Confirmed"&&<small>Contract signed</small>}</div></article>)}</div></section>}

function Contract({contact,cash,close,sign}:{contact:Contact;cash:number;close:()=>void;sign:(id:number,d?:number)=>void}){const total=contact.fee+contact.hotel+contact.fuel+contact.support;return <div className={styles.modalBackdrop}><section className={styles.contract}><button className={styles.close} onClick={close}><X/></button><span className={styles.kicker}>PARTICIPATION PROPOSAL</span><h2>{contact.name}</h2><p>{contact.aircraft} · {contact.country}</p><div className={styles.costs}><Cost name="Appearance fee" value={contact.fee}/><Cost name="Hotel & hospitality" value={contact.hotel}/><Cost name="Fuel provision" value={contact.fuel}/><Cost name="Ground support" value={contact.support}/><Cost name="TOTAL COMMITMENT" value={total} total/></div><div className={styles.requirements}><strong>Operational requirements</strong><p>Secure aircraft parking · dedicated ground crew access · rehearsal slot · crew transport · operations briefing.</p></div><small>Available cash after signing: {money(cash-total)}</small><div className={styles.contractActions}><button onClick={()=>sign(contact.id,.06)}>NEGOTIATE −6%</button><button className={styles.sign} onClick={()=>sign(contact.id)}>ACCEPT & SIGN</button></div></section></div>}
function Cost({name,value,total}:{name:string;value:number;total?:boolean}){return <div className={total?styles.costTotal:""}><span>{name}</span><strong>{money(value)}</strong></div>}
function Feature({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className={styles.feature}>{icon}<div><strong>{title}</strong><span>{text}</span></div></div>}
function Metric({label,value,sub}:{label:string;value:string;sub:string}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>}
const money=(n:number)=>new Intl.NumberFormat("pl-PL",{style:"currency",currency:"PLN",maximumFractionDigits:0}).format(n);
