"use client";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowUpRight, BarChart3, Building2, ChevronRight, CircleDollarSign, Handshake, Megaphone, Plane, ShieldCheck, Ticket, Users, X } from "lucide-react";
import { addDays,daysBetween,formatDate,loadGame,money,readiness,saveGame,seasonMilestones,sponsorOffer,type Contact,type SaveGame,type Sponsor,type Status } from "../lib/game";
import { t } from "../lib/i18n";
import ThemeToggle from "./ThemeToggle";
import styles from "../app/page.module.css";

const sections=[
 ["centrum","center",BarChart3],["operacje","operations",ShieldCheck],["uczestnicy","participants",Plane],["sponsorzy","sponsors",Handshake],["zespol","team",Users],["infrastruktura","infrastructure",Building2],["bilety","tickets",Ticket],["marketing","marketing",Megaphone],["finanse","finance",CircleDollarSign]
] as const;

const modules:Record<string,{eyebrow:string;title:string;description:string;items:string[]}>={
 operacje:{eyebrow:"OPERACJE",title:"Gotowość operacyjna",description:"Planowanie bezpieczeństwa, lotniska i przepływu wydarzenia.",items:["Plan operacyjny lotniska","Strefa pokazów i bezpieczeństwo","Harmonogram prób i odpraw"]},
 sponsorzy:{eyebrow:"KOMERCJA",title:"Sponsorzy i partnerzy",description:"Buduj przychody komercyjne bez utraty kontroli nad zobowiązaniami.",items:["Lista potencjalnych partnerów","Pakiety sponsorskie","Świadczenia i terminy"]},
 zespol:{eyebrow:"ORGANIZACJA",title:"Zespół i departamenty",description:"Kompetencje organizacji będą wpływać na tempo i jakość przygotowań.",items:["Operacje lotnicze","Bezpieczeństwo i logistyka","Komercja i komunikacja"]},
 infrastruktura:{eyebrow:"LOTNISKO",title:"Infrastruktura wydarzenia",description:"Rozwijaj przestrzeń potrzebną uczestnikom, widzom i służbom.",items:["Płyta i parking statków powietrznych","Strefy publiczności","Zaplecze operacyjne"]},
 bilety:{eyebrow:"SPRZEDAŻ",title:"Bilety i frekwencja",description:"Cena, pojemność i tempo sprzedaży będą kształtować wynik wydarzenia.",items:["Cennik i pule biletów","Prognoza frekwencji","Przychód ze sprzedaży"]},
 marketing:{eyebrow:"KOMUNIKACJA",title:"Marketing wydarzenia",description:"Buduj zasięg i popyt, reagując na siłę programu i moment sezonu.",items:["Kampanie promocyjne","Media i partnerzy","Rozpoznawalność wydarzenia"]}
};

export default function GamePage({section}:{section:string}){
 const router=useRouter(); const [game,setGame]=useState<SaveGame|null>(null); const [selected,setSelected]=useState<number|null>(null);
 useEffect(()=>{const g=loadGame();if(!g){router.replace("/nowa-kariera");return}setGame(g)},[router]);
 useEffect(()=>{if(game)saveGame(game)},[game]);
 const days=game?daysBetween(game.currentDate,game.career.eventDate):0;
 const confirmed=game?.contacts.filter(c=>c.status==="confirmed").length??0;
 const active=sections.some(x=>x[0]===section)?section:"centrum";
 const advance=(amount:number)=>setGame(current=>{if(!current)return current;
  const remaining=daysBetween(current.currentDate,current.career.eventDate);
  const nextDate=addDays(current.currentDate,Math.min(amount,remaining));
  const oldDays=remaining;
  const newDays=daysBetween(nextDate,current.career.eventDate);
  const contacts=current.contacts.map(c=>{if(c.status==="invited"&&c.replyAt&&c.replyAt<=nextDate){return {...c,status:(c.id===4?"declined":"interested") as Status}}return c});
  const participantResponses=contacts.filter((c,i)=>c.status!==current.contacts[i].status).map(c=>c.status==="interested"?`${c.name}: otrzymano pozytywną odpowiedź i wymagania operacyjne.`:`${c.name}: zespół nie jest dostępny w tym sezonie.`);
  const confirmedActs=contacts.filter(c=>c.status==="confirmed").length;
  const sponsors=current.sponsors.map(sp=>{if(sp.status==="contacted"&&sp.replyAt&&sp.replyAt<=nextDate){if(current.reputation<sp.minReputation)return {...sp,status:"declined" as const};return {...sp,status:"offered" as const,offer:sponsorOffer(sp,confirmedActs)}}return sp});
  const sponsorResponses=sponsors.filter((sp,i)=>sp.status!==current.sponsors[i].status).map(sp=>sp.status==="offered"?`${sp.name}: otrzymano ofertę sponsorską na ${money(sp.offer??0)}.`:`${sp.name}: odrzucono propozycję współpracy z powodu zbyt niskiej reputacji wydarzenia.`);
  const crossed=seasonMilestones.filter(m=>oldDays>m.days&&newDays<=m.days&&!current.milestonesSeen.includes(m.days));
  const feed=[...crossed.map(m=>m.text),...sponsorResponses,...participantResponses,...current.feed].slice(0,10);
  return {...current,currentDate:nextDate,contacts,sponsors,feed,milestonesSeen:[...current.milestonesSeen,...crossed.map(m=>m.days)]}
 }); const invite=(id:number)=>setGame(current=>current?{...current,contacts:current.contacts.map(c=>c.id===id?{...c,status:"invited",replyAt:addDays(current.currentDate,4)}:c),feed:["Wysłano zaproszenie do uczestnika. Odpowiedź spodziewana jest w ciągu 4 dni.",...current.feed].slice(0,8)}:current);
 const sign=(id:number,discount=0)=>setGame(current=>{if(!current)return current;const c=current.contacts.find(x=>x.id===id);if(!c)return current;const total=Math.round((c.fee+c.hotel+c.fuel+c.support)*(1-discount));if(total>current.cash)return {...current,feed:["Umowa zablokowana: dostępne środki są niewystarczające.",...current.feed].slice(0,8)};setSelected(null);return {...current,cash:current.cash-total,contacts:current.contacts.map(x=>x.id===id?{...x,status:"confirmed"}:x),feed:[`${c.name}: podpisano umowę na ${money(total)}.`,...current.feed].slice(0,8),transactions:[{id:`participant-${id}-${Date.now()}`,date:current.currentDate,label:`Umowa: ${c.name}`,amount:-total,category:"participant"},...current.transactions]}});
 const contactSponsor=(id:number)=>setGame(current=>current?{...current,sponsors:current.sponsors.map(sp=>sp.id===id?{...sp,status:"contacted",replyAt:addDays(current.currentDate,5)}:sp),feed:["Wysłano propozycję współpracy sponsorskiej. Odpowiedź spodziewana jest w ciągu 5 dni.",...current.feed].slice(0,10)}:current);
 const negotiateSponsor=(id:number)=>setGame(current=>{if(!current)return current;const sp=current.sponsors.find(x=>x.id===id);if(!sp||sp.status!=="offered"||!sp.offer)return current;const success=current.reputation>=sp.minReputation+4;const nextOffer=success?Math.round(sp.offer*1.1):sp.offer;return {...current,reputation:success?current.reputation+1:current.reputation,sponsors:current.sponsors.map(x=>x.id===id?{...x,offer:nextOffer,negotiated:true}:x),feed:[success?`${sp.name}: negocjacje zakończone sukcesem. Oferta wzrosła do ${money(nextOffer)}.`:`${sp.name}: sponsor nie zwiększył oferty. Obecne warunki pozostają ważne.`,...current.feed].slice(0,10)}}); 
 const acceptSponsor=(id:number)=>setGame(current=>{if(!current)return current;const sp=current.sponsors.find(x=>x.id===id);if(!sp||sp.status!=="offered"||!sp.offer)return current;return {...current,cash:current.cash+sp.offer,reputation:Math.min(100,current.reputation+2),sponsors:current.sponsors.map(x=>x.id===id?{...x,status:"partner"}:x),feed:[`${sp.name}: podpisano umowę sponsorską na ${money(sp.offer)}.`,...current.feed].slice(0,10),transactions:[{id:`sponsor-${id}-${Date.now()}`,date:current.currentDate,label:`Sponsor: ${sp.name}`,amount:sp.offer,category:"sponsor"},...current.transactions]}});

 if(!game)return <main className={styles.loading}><Plane size={18}/><span>Wczytywanie centrum operacyjnego…</span></main>;
 return <main className={styles.gameShell}>
  <aside className={styles.sidebar}><div className={styles.gameBrand}><span className={styles.mark}><Plane size={17}/></span><div><b>AIRSHOW MANAGER</b><small>SEZON 01</small></div></div><nav>{sections.map(([slug,key,Icon])=><button key={slug} onClick={()=>router.push(`/gra/${slug}`)} className={active===slug?styles.navActive:""}><Icon size={16}/><span>{t(game.locale,`nav.${key}` as any)}</span></button>)}</nav><div className={styles.sidebarActions}><ThemeToggle/><button type="button" onClick={()=>router.push("/")}>Strona główna</button></div><div className={styles.eventChip}><span>AKTYWNE WYDARZENIE</span><b>{game.career.eventName}</b><small>{formatDate(game.career.eventDate)}</small></div></aside>
  <section className={styles.gameMain}><header className={styles.gameHeader}><div><span>{active==="centrum"?"CENTRUM DOWODZENIA":t(game.locale,`nav.${sections.find(x=>x[0]===active)?.[1]}` as any).toUpperCase()}</span><h1>{game.career.eventName}</h1><p>{game.career.location} · {formatDate(game.career.eventDate)}</p></div><div className={styles.clock}><div><b>{days}</b><span>DNI DO POKAZU</span></div><div><button onClick={()=>advance(1)}>+1 dzień</button><button onClick={()=>advance(7)}>+7 dni</button></div></div></header>
  {active==="centrum"&&<Center game={game}/>}
  {active==="uczestnicy"&&<Participants game={game} invite={invite} open={setSelected}/>}
  {active==="finanse"&&<Finance game={game}/>}
  {active==="sponsorzy"&&<Sponsors game={game} contact={contactSponsor} negotiate={negotiateSponsor} accept={acceptSponsor}/>}
  {!["centrum","uczestnicy","finanse","sponsorzy"].includes(active)&&<Module section={active}/>}
  </section>
  {selected&&<Contract contact={game.contacts.find(c=>c.id===selected)!} cash={game.cash} close={()=>setSelected(null)} sign={sign}/>}
 </main>
}

function Center({game}:{game:SaveGame}){const days=daysBetween(game.currentDate,game.career.eventDate);const confirmed=game.contacts.filter(c=>c.status==="confirmed").length;const ready=readiness(game);return <div className={styles.dashboard}>
 <section className={styles.statusRail}><div><span>FAZA SEZONU</span><b>{days>240?"Fundamenty":days>90?"Rozwój programu":"Finalizacja"}</b></div><div><span>NAJBLIŻSZY CEL</span><b>{confirmed<2?"Potwierdź co najmniej 2 uczestników":"Rozwijaj komercję i operacje"}</b></div><div><span>RYZYKO BUDŻETOWE</span><b className={game.cash/game.career.budget>.45?styles.good:styles.warn}>{game.cash/game.career.budget>.45?"Niskie":"Podwyższone"}</b></div></section>
 <section className={styles.kpiGrid}><Kpi label="Dostępne środki" value={money(game.cash)} note={`${Math.round(game.cash/game.career.budget*100)}% budżetu startowego`}/><Kpi label="Potwierdzony program" value={String(confirmed)} note="podpisane umowy"/><Kpi label="Reputacja" value={game.reputation+" / 100"} note="poziom organizatora"/><Kpi label="Gotowość" value={ready+"%"} note="stan całej organizacji"/></section>
 <section className={styles.dashboardGrid}><article className={styles.surface}><PanelHead overline="PRIORYTETY" title="Najbliższe decyzje" meta="4 OTWARTE"/>{[["01","Potwierdź uczestnika","Program lotniczy"],["02","Zbuduj bazę sponsorów","Komercja"],["03","Ustal strategię biletową","Sprzedaż"],["04","Przygotuj plan operacyjny","Operacje"]].map(([n,title,area])=><div className={styles.priority} key={n}><span>{n}</span><div><b>{title}</b><small>{area}</small></div><ChevronRight size={15}/></div>)}</article>
 <article className={styles.surface}><PanelHead overline="GOTOWOŚĆ" title="Obszary organizacji" meta={ready+"%"}/>{[["Program",Math.min(100,confirmed*24)],["Finanse",Math.round(game.cash/game.career.budget*100)],["Operacje",12],["Komunikacja",6]].map(([name,value])=><div className={styles.readinessRow} key={name as string}><div><span>{name}</span><b>{value}%</b></div><i><em style={{width:`${value}%`}}/></i></div>)}</article></section>
 <section className={styles.surface}><PanelHead overline="DZIENNIK" title="Ostatnie wydarzenia" meta={formatDate(game.currentDate)}/><div className={styles.activity}>{game.feed.map((x,i)=><div key={i}><span>D-{days}</span><p>{x}</p></div>)}</div></section>
 </div>}

function Participants({game,invite,open}:{game:SaveGame;invite:(id:number)=>void;open:(id:number)=>void}){return <div className={styles.modulePage}><ModuleHeader eyebrow="PROGRAM LOTNICZY" title="Uczestnicy" description="Buduj program wydarzenia. Zaproszenia potrzebują czasu, a każda podpisana umowa obciąża budżet." meta={`${game.contacts.filter(c=>c.status==="confirmed").length} potwierdzonych`}/><div className={styles.tableHeader}><span>ZESPÓŁ / STATEK</span><span>KRAJ</span><span>KOSZT BAZOWY</span><span>STATUS</span><span/></div><div className={styles.participantTable}>{game.contacts.map(c=><div className={styles.participantRow} key={c.id}><div><b>{c.name}</b><span>{c.aircraft}</span></div><span>{c.country}</span><span>{money(c.fee)}</span><span className={styles["status_"+c.status]}>{t(game.locale,`status.${c.status}` as any)}</span><div>{c.status==="available"&&<button onClick={()=>invite(c.id)}>Wyślij zaproszenie</button>}{c.status==="invited"&&<small>Odpowiedź: {c.replyAt&&formatDate(c.replyAt)}</small>}{c.status==="interested"&&<button onClick={()=>open(c.id)}>Warunki umowy</button>}{c.status==="confirmed"&&<small>Umowa aktywna</small>}{c.status==="declined"&&<small>Niedostępny</small>}</div></div>)}</div></div>}

function Sponsors({game,contact,negotiate,accept}:{game:SaveGame;contact:(id:number)=>void;negotiate:(id:number)=>void;accept:(id:number)=>void}){const partners=game.sponsors.filter(s=>s.status==="partner");const secured=partners.reduce((sum,s)=>sum+(s.offer??0),0);return <div className={styles.modulePage}><ModuleHeader eyebrow="KOMERCJA" title="Sponsorzy i partnerzy" description="Buduj finansowanie wydarzenia. Siła programu i reputacja wpływają na wartość ofert, a każda umowa niesie konkretne zobowiązania." meta={`${partners.length} aktywnych · ${money(secured)}`}/><section className={styles.sponsorSummary}><Kpi label="Przychód sponsorski" value={money(secured)} note="podpisane partnerstwa"/><Kpi label="Aktywne rozmowy" value={String(game.sponsors.filter(s=>["contacted","offered"].includes(s.status)).length)} note="kontakty i oferty"/><Kpi label="Reputacja" value={game.reputation+" / 100"} note="wpływa na dostęp do marek"/></section><div className={styles.sponsorGrid}>{game.sponsors.map(sp=><SponsorCard key={sp.id} sponsor={sp} reputation={game.reputation} contact={contact} negotiate={negotiate} accept={accept}/>)}</div></div>}

function SponsorCard({sponsor,reputation,contact,negotiate,accept}:{sponsor:Sponsor;reputation:number;contact:(id:number)=>void;negotiate:(id:number)=>void;accept:(id:number)=>void}){const labels={prospect:"Potencjalny partner",contacted:"Oczekiwanie na odpowiedź",offered:"Oferta otrzymana",partner:"Aktywny sponsor",declined:"Brak współpracy"} as const;const locked=reputation<sponsor.minReputation;return <article className={styles.sponsorCard}><header><div><span>{sponsor.tier} · {sponsor.industry}</span><h3>{sponsor.name}</h3></div><b className={styles["sponsor_"+sponsor.status]}>{labels[sponsor.status]}</b></header><div className={styles.sponsorValue}><span>POTENCJAŁ UMOWY</span><strong>{sponsor.offer?money(sponsor.offer):`od ${money(sponsor.baseOffer)}`}</strong></div><p>{sponsor.requirement}</p><div className={styles.sponsorMeta}><span>Wymagana reputacja <b>{sponsor.minReputation}</b></span><span>Bonus za potwierdzony pokaz <b>+{money(sponsor.perConfirmedAct)}</b></span></div><footer>{sponsor.status==="prospect"&&<button disabled={locked} onClick={()=>contact(sponsor.id)}>{locked?`Wymaga reputacji ${sponsor.minReputation}`:"Rozpocznij rozmowy"}</button>}{sponsor.status==="contacted"&&<span>Odpowiedź: {sponsor.replyAt&&formatDate(sponsor.replyAt)}</span>}{sponsor.status==="offered"&&<><button disabled={sponsor.negotiated} onClick={()=>negotiate(sponsor.id)}>{sponsor.negotiated?"Negocjacje zakończone":"Negocjuj warunki"}</button><button className={styles.primarySmall} onClick={()=>accept(sponsor.id)}>Podpisz umowę</button></>}{sponsor.status==="partner"&&<span>Umowa aktywna · środki zaksięgowane</span>}{sponsor.status==="declined"&&<span>Spróbuj ponownie w kolejnym sezonie</span>}</footer></article>}

function Finance({game}:{game:SaveGame}){const spent=game.transactions.filter(x=>x.amount<0).reduce((a,b)=>a-b.amount,0);return <div className={styles.modulePage}><ModuleHeader eyebrow="FINANSE" title="Kontrola budżetu" description="Każde zobowiązanie trafia do historii finansowej. Ten moduł stanie się podstawą cashflow, sponsorów i sprzedaży biletów." meta={money(game.cash)}/><section className={styles.financeSummary}><Kpi label="Budżet startowy" value={money(game.career.budget)} note="kapitał sezonu"/><Kpi label="Wydatki zakontraktowane" value={money(spent)} note="łączne obciążenia"/><Kpi label="Dostępne środki" value={money(game.cash)} note="bieżące saldo"/></section><article className={styles.surface}><PanelHead overline="REJESTR" title="Historia transakcji" meta={`${game.transactions.length} pozycji`}/><div className={styles.ledger}>{game.transactions.map(x=><div key={x.id}><span>{formatDate(x.date)}</span><b>{x.label}</b><strong className={x.amount>=0?styles.good:styles.expense}>{x.amount>=0?"+":""}{money(x.amount)}</strong></div>)}</div></article></div>}

function Module({section}:{section:string}){const m=modules[section]??modules.operacje;return <div className={styles.modulePage}><ModuleHeader eyebrow={m.eyebrow} title={m.title} description={m.description} meta="W ROZWOJU"/><div className={styles.moduleRoadmap}>{m.items.map((x,i)=><article key={x}><span>0{i+1}</span><div><b>{x}</b><p>Moduł został przygotowany w strukturze aplikacji i będzie rozwijany jako część symulacji sezonu.</p></div><ArrowUpRight size={17}/></article>)}</div></div>}

function Contract({contact,cash,close,sign}:{contact:Contact;cash:number;close:()=>void;sign:(id:number,d?:number)=>void}){const total=contact.fee+contact.hotel+contact.fuel+contact.support;return <div className={styles.modalBackdrop}><section className={styles.contract}><button className={styles.close} onClick={close}><X size={19}/></button><span className={styles.eyebrow}>WARUNKI UCZESTNICTWA</span><h2>{contact.name}</h2><p>{contact.aircraft} · {contact.country}</p><div className={styles.costList}><Cost label="Opłata za udział" value={contact.fee}/><Cost label="Hotel i obsługa gości" value={contact.hotel}/><Cost label="Paliwo" value={contact.fuel}/><Cost label="Obsługa naziemna" value={contact.support}/><Cost label="Łączne zobowiązanie" value={total} total/></div><div className={styles.requirementBox}><ShieldCheck size={18}/><div><b>Wymagania operacyjne</b><p>Bezpieczny parking statku powietrznego, obsługa naziemna, slot treningowy, transport załogi i odprawa operacyjna.</p></div></div><div className={styles.balanceAfter}><span>Saldo po podpisaniu</span><b>{money(cash-total)}</b></div><div className={styles.modalActions}><button onClick={()=>sign(contact.id,.06)}>Negocjuj −6%</button><button onClick={()=>sign(contact.id)}>Akceptuj i podpisz</button></div></section></div>}

function Kpi({label,value,note}:{label:string;value:string;note:string}){return <article className={styles.kpi}><span>{label}</span><b>{value}</b><small>{note}</small></article>}
function PanelHead({overline,title,meta}:{overline:string;title:string;meta:string}){return <header className={styles.panelHead}><div><span>{overline}</span><h3>{title}</h3></div><b>{meta}</b></header>}
function ModuleHeader({eyebrow,title,description,meta}:{eyebrow:string;title:string;description:string;meta:string}){return <header className={styles.moduleHeader}><div><span>{eyebrow}</span><h2>{title}</h2><p>{description}</p></div><b>{meta}</b></header>}
function Cost({label,value,total}:{label:string;value:number;total?:boolean}){return <div className={total?styles.costTotal:""}><span>{label}</span><b>{money(value)}</b></div>}
